---
build_from:
  aarch64: ghcr.io/hassio-addons/base:15.0.3
  amd64: ghcr.io/hassio-addons/base:15.0.3
  armv7: ghcr.io/hassio-addons/base:15.0.3
codenotary:
  signer: lucio.tarantino@gmail.com
  base_image: codenotary@frenck.dev
args:
  HDDTEMP_VERSION: "0.3-beta15"
